version: '3.4'

services:
  webserver:
    image: nginx:1.22-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: unless-stopped

  app:
    build:
      context: ./node
    volumes:
      - ./app:/opt/app/src
    ports:
      - "8080:8080"
    environment:
      - FRONTEND_ENV=${FRONTEND_ENV}