version: '3.2'
services:
  webserver:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/default.template.conf:/etc/nginx/conf.d/default.template
      - ./app:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
  app:
    build:
      context: node
      target: ${FRONTEND_STAGE}
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"